### ISSUE TITLE
How can I remove the black rectangle around the root breadcrumb?

### ISSUE THREAD

**Issue by ajtruckle** [mtekk/Breadcrumb-NavXT#317]
I have added breadcrumb support to a website and things are fine for the home page:

Site: https://trucklesoft.org.uk/

Snapshot:

![Image](https://github.com/user-attachments/assets/ac81354e-833a-409d-b02e-80f8bf3bbe82)

But when you drill down to an article it is different:

Site: https://trucklesoft.org.uk/2025/04/25/the-journey-behind-meeting-schedule-assistant/

Snapshot:

![Image](https://github.com/user-attachments/assets/35725bb1-2aa5-4543-bebe-d522cd0c8ff7)

How can we remove the black rectangle? My publictalksoftware.co.uk website suffers the same visual issue.

I am using the latest version of the plugin.

**Comment by mtekk** [comment]
You'll need to use your web browser's inspector to see what CSS is getting applied to that element and see why there is the black box/vertical bar. Since Breadcrumb NavXT does not ship with front end CSS, it is likely your theme that is providing the CSS rules that are resulting in this.

On the linked page, it seems `https://www.publictalksoftware.co.uk/wp-content/cache/autoptimize/css/autoptimize_single_cc76d97f56472c0366527a89ae39bff0.css?ver=1.0.14` is to blame, there is something that sets the font size to .866667em, which the rounding causes a scaling error on the thing that causes the arrow/triangle.

**Comment by ajtruckle** [comment]
```css
#topbar, div.menu-side-box, .below-header, .post-gridunit-subtitle, .hk-gridunit-subtitle, .verticalcarousel-subtitle {
    font-size: 0.86666667em;
    line-height: 1.384615em;
}
```

That is part of the theme it seems.
